Repository RedHatInsights/insights-frontend-components, pull requests merged in 2019-02, with the labels that each got.

#279 updating styling for expandable rules card
  package-lock.json
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
  src/SmartComponents/Inventory/applications/advisor/advisor.scss
Labels: enhancement

#293 Use total_risk rather than severity for 'Total Risk'
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
Labels: bug

#294 Swapping icons for Detected Issues/Steps to Resolve
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
Labels: bug

#323 Add min width to pagination input
  src/PresentationalComponents/Pagination/PaginationNav.js
Labels: bug

#336 Allow Shield impact prop to accept numerical values
  doc/components/shield.md
  src/PresentationalComponents/Shield/Shield.js
  src/PresentationalComponents/Shield/Shield.test.js
  src/PresentationalComponents/Shield/__snapshots__/Shield.test.js.snap
  src/PresentationalComponents/Shield/consts.js
Labels: bug, enhancement
