Repository RedHatInsights/insights-frontend-components, pull requests merged in 2019-03, with the labels that each got.

#340 When active rule index is 0 ensure we display it first
  src/SmartComponents/Inventory/applications/advisor/Advisor.js
Labels: bug

#337 Fix pagination total of system rules table
  src/SmartComponents/Inventory/applications/compliance/SystemRulesTable.js
Labels: bug

#338 Add templates for issue and pull requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/new_component.md
Labels: enhancement

#318 Allow filtering of inventory over fqdn, id or display_name
  src/SmartComponents/Inventory/Filter/Filter.js
  src/api/inventory.js
Labels: enhancement

#328 Systems Exposed Table - Redesigned table to new wireframe design
  src/SmartComponents/Inventory/applications/vulnerabilities/DataMapper.js
  src/SmartComponents/Inventory/applications/vulnerabilities/Vulnerabilities.js
  src/SmartComponents/Inventory/applications/vulnerabilities/VulnerabilitiesCveTable.js
  src/SmartComponents/Inventory/applications/vulnerabilities/vulnerabilities.scss
  src/Utilities/helpers.js
Labels: enhancement

#320 Add new component skeleton table
  src/PresentationalComponents/SkeletonTable/SkeletonTable.js
  src/PresentationalComponents/SkeletonTable/SkeletonTable.test.js
  src/PresentationalComponents/SkeletonTable/__snapshots__/SkeletonTable.test.js.snap
  src/PresentationalComponents/SkeletonTable/index.js
Labels: new component

#343 updating TableToolbar to use Toolbar layout <?.?.x>
  doc/components/tableToolbar.md
  src/PresentationalComponents/TableToolbar/TableToolbar.js
  src/PresentationalComponents/TableToolbar/__snapshots__/TableToolbar.test.js.snap
Labels: enhancement

#335 patternfly-next > patternfly
  config/webpack-build.plugins.js
  demo/styles.scss
  package-lock.json
  package.json
  src/App.scss
  src/Charts/Gauge/gauge.scss
  src/PresentationalComponents/Input/input.scss
  src/PresentationalComponents/Pagination/pagination.scss
  src/PresentationalComponents/Reboot/reboot.scss
  src/PresentationalComponents/SimpleTableFilter/simple-table-filter.scss
  src/PresentationalComponents/Table/table.scss
  src/SmartComponents/Inventory/InventoryList.scss
  src/SmartComponents/Inventory/applications/advisor/Advisor.js
  src/SmartComponents/Remediations/steps/ErrorStep.scss
  src/Utilities/_variables.scss
Labels: enhancement

#347 adding support for footer in TableToolbar <?.?.x>
  doc/components/tableToolbar.md
  src/PresentationalComponents/TableToolbar/TableToolbar.js
  src/PresentationalComponents/TableToolbar/TableToolbar.scss
  src/PresentationalComponents/TableToolbar/TableToolbar.test.js
  src/PresentationalComponents/TableToolbar/__snapshots__/TableToolbar.test.js.snap
Labels: enhancement

#321 Update entity table
  doc/components/inventory/inventory.md
  package-lock.json
  package.json
  src/SmartComponents/Inventory/Actions.js
  src/SmartComponents/Inventory/EntityTable.js
  src/SmartComponents/Inventory/EntityTableToolbar.js
  src/SmartComponents/Inventory/Filter/Filter.js
  src/SmartComponents/Inventory/Inventory.js
  src/SmartComponents/Inventory/InventoryList.scss
  src/SmartComponents/Inventory/Pagination.js
Labels: enhancement

#361 Insights api changed, report.resoution.has_playbook now, fixes kba fetch
  src/SmartComponents/Inventory/applications/advisor/Advisor.js
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
Labels: bug

#362 Adding spinner component <?.x.?>
  doc/components/spinner.md
  src/PresentationalComponents/Spinner/Spinner.js
  src/PresentationalComponents/Spinner/Spinner.test.js
  src/PresentationalComponents/Spinner/__snapshots__/Spinner.test.js.snap
  src/PresentationalComponents/Spinner/index.js
  src/PresentationalComponents/Spinner/spinner.scss
  src/index.js
Labels: enhancement, new component

#364 Inheriting whitespace on `code` fixes this issue
  src/SmartComponents/Inventory/applications/advisor/advisor.scss
Labels: bug

#359 Update Battery
  src/PresentationalComponents/Battery/Battery.js
  src/PresentationalComponents/Battery/CriticalBattery.js
  src/PresentationalComponents/Battery/HighBattery.js
  src/PresentationalComponents/Battery/LowBattery.js
  src/PresentationalComponents/Battery/MediumBattery.js
  src/PresentationalComponents/Battery/NullBattery.js
  src/PresentationalComponents/Battery/__snapshots__/Batery.test.js.snap
  src/PresentationalComponents/Battery/battery.scss
  src/Utilities/_variables.scss
Labels: enhancement, needs UX
