Repository RedHatInsights/insights-frontend-components, pull requests merged in 2019-04, with the labels that each got.

#367 Updating battery to take up required space
  src/PresentationalComponents/Battery/Battery.js
  src/PresentationalComponents/Battery/__snapshots__/Batery.test.js.snap
  src/PresentationalComponents/Battery/battery.scss
Labels: bug

#370 Adds external link icon tooling to template processor
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
Labels: enhancement

#374 Updates insights app to conform to api changes 🍽
  src/SmartComponents/Inventory/applications/advisor/Advisor.js
Labels: enhancement

#369 Use inventory JS client instead of fetch
  package-lock.json
  package.json
  src/SmartComponents/Inventory/InventoryList.js
  src/api/interceptors.js
  src/api/inventory.js
Labels: enhancement

#379 Vulnerability: Start using new filter component
  src/PresentationalComponents/Filters/FilterInput.js
  src/SmartComponents/Inventory/applications/vulnerabilities/StatusDropdown.js
  src/SmartComponents/Inventory/applications/vulnerabilities/VulnerabilitiesCveTable.js
  src/SmartComponents/Inventory/applications/vulnerabilities/VulnerabilitiesCveTableToolbar.js
  src/SmartComponents/Inventory/applications/vulnerabilities/VulnerabilitiesCves.js
  src/SmartComponents/Inventory/applications/vulnerabilities/constants.js
  src/api/vulnerabilities.js
Labels: onhold

#382 Removes fetch failed toast, adds no system text
  src/SmartComponents/Inventory/applications/advisor/Advisor.js
Labels: bug

#384 Restore notifications for ansible remediations
  src/SmartComponents/Inventory/applications/advisor/Advisor.js
Labels: bug

#406 Regex replaces all instances, template literal (string) only 1st (ul instance)
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
Labels: bug

#409 Adds external link icons to reports, this is fine as static markup
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
Labels: bug

#412 Undo the external icon report markup
  src/SmartComponents/Inventory/applications/advisor/ExpandableRulesCard.js
Labels: bug
